project:
  type: website

website:
  title: "SiPBA Research Lab"
  description: "Demo projects, experiments, debugging data and so on from the [SiPBA Research Lab](https://sipba.github.io/)"
  site-url: https://sipba.github.io/
  favicon: images/logos/favicon.webp
  twitter-card: true
  page-footer: 
    left: |
      <a href="https://creativecommons.org">SiPBA</a> © 2025 by <a href="https://creativecommons.org">SiPBA</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/nc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;">
    right: "This website is built with [Quarto](https://quarto.org/). [Terms of Use](https://www.ugr.es/condiciones-legales)"
    background: warning
    foreground: white
  navbar:
    title: ""
    background: primary
    search: true
    logo: images/logos/SinFondoClaro.png
    right:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research
      - publications.qmd
      - posts.qmd
    tools: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/SiPBA
        target: _blank
      - icon: envelope-fill
        text: ""
        href: contact.qmd
        aria-label: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    grid:
      body-width: 1000px
    
execute:
  freeze: auto
# navbar: 
#    background: "#222322"
#    foreground: "#FFFFFF"