project:
  type: website
  output-dir: docs

website:
  title: "SiPBA Research Lab"
  description: "Demo projects, experiments, debugging data and so on from the [SiPBA Research Lab](https://sipba.github.io/)"
  site-url: https://sipba.github.io/
  favicon: /images/logo/favicon.webp
  navbar:
    title: ""
    background: primary
    search: true
    logo: images/logos/SinFondoClaro.png
    right:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research
      - publications.qmd
      - posts.qmd
      - icon: github # add icons as navbar buttons
        href: https://github.com/SiPBA
        target: _blank

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

# navbar: 
#    background: "#222322"
#    foreground: "#FFFFFF"